# Generated by Django 2.2.5 on 2019-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone_number', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(max_length=100, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('origin', models.CharField(choices=[('Walkin', 'Walkin'), ('Phone', 'Phone'), ('Website', 'Website')], max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted')], default='Pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
